### ISSUE TITLE
upgrade mikro-orm to 5.1, Cannot find module '@mikro-orm/sql-highlighter' 

### ISSUE THREAD

**Issue by devgamesgalo** [mikro-orm/sql-highlighter#15]
Hi, Help please I get this error when I upgrade mikro-orm to 5.1 :
Cannot find module '@mikro-orm/sql-highlighter' or its corresponding type declarations.ts(2307)

**Comment by B4nan** [comment]
If you need help, provide some reproduction, I have no idea what you are talking about, or even what exact version of what exact package you mean.

Note that you need to explicitly install the highlighter if you want to use it.

**Comment by devgamesgalo** [comment]
I'm sorry for my late reply, the latest version of the @mikro-orm/core 5.1 package is not compatible with mikro-orm
/
sql-highlighter 1.0.1 please note that mikro-orm/sql-highlighter is already installed

Compilation error in ../src/config/mikro-orm.config.ts
[0] [ERROR] 21:31:56 ⨯ Unable to compile TypeScript:
[0] src/config/mikro-orm.config.ts(7,32): error TS2307: Cannot find module '@mikro-orm/sql-highlighter' or its corresponding type declarations.
[0] 

```
import {
  MemoryCacheAdapter,
  Options,
  ReflectMetadataProvider
} from '@mikro-orm/core'
import { PostgreSqlDriver } from '@mikro-orm/postgresql'
---line 7 ----> import { SqlHighlighter } from '@mikro-orm/sql-highlighter'
import { CustomError } from '@/types/CustomError'
import { BaseEntity } from '@/entity/BaseEntity'
```
